# Generated by Django 5.1.3 on 2024-12-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingcategory',
            name='category_image',
            field=models.ImageField(default=1, upload_to='clothing/category'),
            preserve_default=False,
        ),
    ]
