# Generated by Django 5.1.3 on 2024-12-28 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0002_clothingcategory_category_image'),
        ('vendors', '0015_remove_vendor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingcategory',
            name='store',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
    ]
