# Generated by Django 5.1.3 on 2024-12-28 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0003_clothingcategory_store'),
        ('vendors', '0015_remove_vendor_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingcategory',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor'),
        ),
    ]
