# Generated by Django 5.1.3 on 2024-12-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0004_alter_clothingcategory_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
