# Generated by Django 5.1.3 on 2024-12-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0005_alter_clothingcategory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='color_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='color',
        ),
        migrations.AddField(
            model_name='clothing',
            name='colors',
            field=models.ManyToManyField(related_name='clothing_items', to='fashion.color'),
        ),
    ]
