# Generated by Django 5.1.3 on 2024-12-28 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0006_color_remove_clothing_color_clothing_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subcategory_image', models.ImageField(upload_to='clothing/subcategory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='fashion.clothingcategory')),
            ],
        ),
        migrations.AddField(
            model_name='clothing',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothing_items', to='fashion.clothingsubcategory'),
        ),
    ]
