# Generated by Django 5.1.3 on 2025-01-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0008_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
