# Generated by Django 5.1.3 on 2025-01-08 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0011_fashionreport_fashionreview_fashionwishlist'),
        ('vendors', '0016_vendor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='vendors.vendor'),
            preserve_default=False,
        ),
    ]
