# Generated by Django 5.1.3 on 2025-01-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0012_coupon_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
