# Generated by Django 5.1.3 on 2025-01-14 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0013_coupon_is_admin'),
        ('vendors', '0017_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='vendors.category'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothing_items', to='vendors.category'),
        ),
        migrations.DeleteModel(
            name='ClothingCategory',
        ),
    ]
