# Generated by Django 5.1.3 on 2025-01-16 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0014_alter_clothingsubcategory_category_and_more'),
        ('vendors', '0020_remove_category_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingsubcategory',
            name='enable_subcategory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clothingsubcategory',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='clothing_subcategories', to='vendors.vendor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothingsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_subcategories', to='vendors.category'),
        ),
    ]
