# Generated by Django 5.1.3 on 2025-01-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0015_clothingsubcategory_enable_subcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='colors',
        ),
        migrations.AddField(
            model_name='clothing',
            name='colors',
            field=models.JSONField(default=list, help_text="List of colors with details, e.g., [{'color_name': 'Red', 'color_image': '/path/to/image.jpg', 'price': 1000.00}]"),
        ),
    ]
