# Generated by Django 5.1.3 on 2025-01-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0016_remove_clothing_colors_clothing_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='available_sizes',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='stock',
        ),
        migrations.AlterField(
            model_name='clothing',
            name='colors',
            field=models.JSONField(default=list, help_text="List of color variants with sizes, prices and stock. Format: [{'color_name': 'Red', 'color_image': '/path/to/image.jpg', 'sizes': [{'size': 'S', 'price': 1000.00, 'stock': 10}, ...]}]"),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base price for this item', max_digits=10),
        ),
    ]
