# Generated by Django 5.1.3 on 2025-02-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0017_remove_clothing_available_sizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
