# Generated by Django 5.1.4 on 2025-03-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0018_clothing_wholesale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
