# Generated by Django 5.1.4 on 2025-03-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0019_clothing_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='colors',
            field=models.JSONField(default=list, help_text="List of color variants with sizes, prices and stock. Format: [{'color_name': 'Red', 'color_image': '/path/to/image.jpg', 'sizes': [{'size': 'S', 'price': 1000.00, 'stock': 10, 'offerprice':1000.00}, ...]}]"),
        ),
    ]
