# Generated by Django 5.1.4 on 2025-03-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0020_alter_clothing_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Base price for this item', max_digits=10, null=True),
        ),
    ]
