# Generated by Django 5.1.4 on 2025-03-18 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0021_alter_clothing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='colors',
            field=models.JSONField(),
        ),
        migrations.CreateModel(
            name='ClothingColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('color_image', models.ImageField(upload_to='colors/')),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothcolors', to='fashion.clothing')),
            ],
        ),
        migrations.CreateModel(
            name='ClothingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='fashion.clothingcolor')),
            ],
        ),
    ]
