# Generated by Django 5.1.4 on 2025-03-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0022_alter_clothing_colors_clothingcolor_clothingsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingcolor',
            name='color_image',
            field=models.ImageField(null=True, upload_to='colors/'),
        ),
    ]
