# Generated by Django 5.1.4 on 2025-03-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0023_alter_clothingcolor_color_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='colors',
            field=models.JSONField(null=True),
        ),
    ]
