# Generated by Django 5.1.4 on 2025-03-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0024_alter_clothing_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingcolor',
            name='color_image',
        ),
        migrations.AddField(
            model_name='clothingcolor',
            name='color_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
