# Generated by Django 5.1.4 on 2025-03-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0025_remove_clothingcolor_color_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='colors',
            field=models.JSONField(default=list, null=True),
        ),
    ]
