# Generated by Django 5.1.4 on 2025-04-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0026_alter_clothing_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='is_wishlisted',
            field=models.BooleanField(default=False),
        ),
    ]
