# Generated by Django 5.1.4 on 2025-04-22 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion', '0027_clothing_is_wishlisted'),
        ('vendors', '0028_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clothing_items', to='vendors.subcategory'),
        ),
    ]
