# Generated by Django 5.1.4 on 2025-04-25 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_tracking', '0002_alter_couponusage_coupon'),
        ('fashion', '0028_alter_clothing_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponusage',
            name='coupon',
        ),
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='user',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='CouponUsage',
        ),
    ]
