# Generated by Django 5.1.3 on 2024-12-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address_email_address_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='email',
        ),
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
    ]
