# Generated by Django 5.1.3 on 2025-01-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_address_email_remove_address_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp_created_at',
        ),
    ]
