# Generated by Django 5.1.4 on 2025-03-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_coupon'),
        ('vendors', '0027_vendor_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourite_vendors',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='vendors.vendor'),
        ),
    ]
