# Generated by Django 5.1.4 on 2025-04-10 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_unifiedwishlist'),
        ('vendors', '0027_vendor_is_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_vendor_links', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_user_links', to='vendors.vendor')),
            ],
            options={
                'unique_together': {('user', 'vendor')},
            },
        ),
    ]
