# Generated by Django 5.1.4 on 2025-04-16 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_favoritevendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigBuyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=255)),
                ('quantity_in_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_people', models.PositiveIntegerField()),
                ('preferred_delivery_date', models.DateField()),
                ('special_occasion', models.CharField(blank=True, max_length=255, null=True)),
                ('diet_category', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
