# Generated by Django 5.1.4 on 2025-04-17 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_bigbuyorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact_number',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
