# Generated by Django 5.1.4 on 2025-04-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_address_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_new_customer',
            field=models.BooleanField(default=False),
        ),
    ]
