# Generated by Django 5.1.4 on 2025-04-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_coupon_created_by_alter_coupon_vendor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coupon',
            table='users_coupon',
        ),
    ]
