# Generated by Django 5.1.3 on 2025-01-14 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('vendors', '0017_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcoupon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.category'),
        ),
        migrations.AlterField(
            model_name='foodoffer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.category'),
        ),
    ]
