# Generated by Django 3.2.10 on 2024-11-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodproduct', '0002_auto_20241106_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dish_image',
        ),
    ]
