# Generated by Django 5.1.3 on 2024-11-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodproduct', '0003_remove_dish_dish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='Description',
            field=models.CharField(default='Category Description', max_length=1000),
        ),
    ]
