# Generated by Django 5.1.3 on 2024-11-11 09:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodproduct', '0005_foodcategory_created_at_foodsubcategories_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishaddon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishaddon',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dishaddon',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='dishaddon',
            name='is_offer_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dishaddon',
            name='is_popular_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dishaddon',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='DishAddonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dish_addon_images/')),
                ('dish_addon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_images', to='foodproduct.dishaddon')),
            ],
        ),
    ]
