# Generated by Django 5.1.3 on 2024-12-20 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodproduct', '0009_alter_dishreview_user_alter_wishlist_user'),
        ('users', '0006_remove_address_email_remove_address_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='foodproduct.dish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_reports', to='users.customuser')),
            ],
        ),
    ]
