# Generated by Django 5.1.3 on 2025-01-08 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodproduct', '0012_foodcoupon_foodcouponusage'),
        ('vendors', '0016_vendor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcoupon',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='foodcoupons', to='vendors.vendor'),
            preserve_default=False,
        ),
    ]
