# Generated by Django 5.1.3 on 2025-01-14 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodproduct', '0013_foodcoupon_vendor'),
        ('vendors', '0017_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='store',
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='vendors.category'),
        ),
        migrations.AlterField(
            model_name='foodsubcategories',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.category'),
        ),
    ]
