# Generated by Django 5.1.3 on 2025-01-14 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodproduct', '0014_remove_foodcategory_store_alter_dish_category_and_more'),
        ('offers', '0002_alter_foodcoupon_category_alter_foodoffer_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodCategory',
        ),
    ]
