# Generated by Django 5.1.3 on 2025-01-16 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodproduct', '0015_delete_foodcategory'),
        ('vendors', '0020_remove_category_vendors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodsubcategories',
            old_name='Enable_subcategory',
            new_name='enable_subcategory',
        ),
        migrations.RemoveField(
            model_name='foodsubcategories',
            name='Sub_category_image',
        ),
        migrations.RemoveField(
            model_name='foodsubcategories',
            name='main_category',
        ),
        migrations.AddField(
            model_name='foodsubcategories',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_subcategories', to='vendors.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodsubcategories',
            name='subcategory_image',
            field=models.ImageField(blank=True, null=True, upload_to='food/subcategory_images/'),
        ),
        migrations.AddField(
            model_name='foodsubcategories',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_subcategories', to='vendors.vendor'),
            preserve_default=False,
        ),
    ]
