# Generated by Django 5.1.3 on 2025-02-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodproduct', '0016_rename_enable_subcategory_foodsubcategories_enable_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='variants',
            field=models.JSONField(default=list, help_text='Store different variants (name, price, stock status) as a dictionary'),
        ),
    ]
