# Generated by Django 5.1.4 on 2025-04-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodproduct', '0019_alter_dish_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='subcategory',
        ),
    ]
