# Generated by Django 5.1.4 on 2025-04-22 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodproduct', '0020_remove_dish_subcategory'),
        ('vendors', '0028_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='vendors.subcategory'),
        ),
    ]
