# Generated by Django 5.1.3 on 2024-12-13 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryproducts', '0004_grocerycategory_description_and_more'),
        ('vendors', '0014_vendor_alternate_email_vendor_otp_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryproducts',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grocery', to='vendors.vendor'),
            preserve_default=False,
        ),
    ]
