# Generated by Django 5.1.3 on 2024-12-20 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryproducts', '0006_alter_grocery_wishlist_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grocery_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='groceryproducts.groceryproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groceryproduct_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
