# Generated by Django 5.1.3 on 2024-12-28 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryproducts', '0007_groceryproductreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryproducts',
            name='image',
        ),
    ]
