# Generated by Django 5.1.3 on 2025-01-08 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryproducts', '0010_rename_grocerycouponusagecoupon_grocerycoupon'),
        ('vendors', '0016_vendor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerycoupon',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grocerycoupons', to='vendors.vendor'),
            preserve_default=False,
        ),
    ]
