# Generated by Django 5.1.3 on 2025-01-14 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryproducts', '0011_grocerycoupon_vendor'),
        ('vendors', '0017_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryproducts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.category'),
        ),
        migrations.AlterField(
            model_name='grocerysubcategories',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.category'),
        ),
        migrations.DeleteModel(
            name='GroceryCategory',
        ),
    ]
