# Generated by Django 5.1.3 on 2025-01-16 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryproducts', '0012_alter_groceryproducts_category_and_more'),
        ('vendors', '0020_remove_category_vendors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocerysubcategories',
            old_name='Enable_subcategory',
            new_name='enable_subcategory',
        ),
        migrations.RemoveField(
            model_name='grocerysubcategories',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='grocerysubcategories',
            name='Sub_category_image',
        ),
        migrations.AddField(
            model_name='grocerysubcategories',
            name='subcategory_image',
            field=models.ImageField(blank=True, null=True, upload_to='grocery/subcategory_images/'),
        ),
        migrations.AddField(
            model_name='grocerysubcategories',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grocery_subcategories', to='vendors.vendor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grocerysubcategories',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grocery_subcategories', to='vendors.category'),
            preserve_default=False,
        ),
    ]
