# Generated by Django 5.1.3 on 2025-02-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceryproducts', '0013_rename_enable_subcategory_grocerysubcategories_enable_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryproducts',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
