# Generated by Django 5.1.4 on 2025-03-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryproducts', '0014_groceryproducts_wholesale_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryproducts',
            old_name='Available',
            new_name='is_available',
        ),
    ]
