# Generated by Django 5.1.4 on 2025-04-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryproducts', '0016_alter_groceryproducts_weights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryproducts',
            name='sub_category',
        ),
    ]
