# Generated by Django 5.1.4 on 2025-04-25 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_tracking', '0001_initial'),
        ('users', '0021_alter_coupon_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='users.coupon'),
        ),
    ]
