# Generated by Django 5.1.4 on 2025-04-25 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_tracking', '0002_alter_couponusage_coupon'),
        ('fashion', '0030_coupon_couponusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='fashion.coupon'),
        ),
    ]
