# Generated by Django 5.1.4 on 2025-04-26 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_checkout_coupon'),
        ('coupon_tracking', '0003_alter_couponusage_coupon'),
        ('users', '0021_alter_coupon_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CouponUsage',
            new_name='UserCouponUsage',
        ),
        migrations.AlterField(
            model_name='usercouponusage',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='users.coupon'),
        ),
    ]
