# Generated by Django 3.2.10 on 2024-11-06 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodproduct', '0002_auto_20241106_1633'),
        ('vendors', '0002_auto_20241024_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='main_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='SubCategories',
        ),
    ]
