# Generated by Django 3.2.10 on 2024-11-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_auto_20241107_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
