# Generated by Django 5.1.3 on 2024-11-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_vendor_is_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='is_vendor',
        ),
    ]
