# Generated by Django 5.1.3 on 2024-11-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_remove_vendor_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_vendor',
            field=models.BooleanField(default=True),
        ),
    ]
