# Generated by Django 5.1.3 on 2024-11-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_vendor_is_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='is_vendor',
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_Grocery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_restaurent',
            field=models.BooleanField(default=False),
        ),
    ]
