# Generated by Django 5.1.3 on 2024-11-09 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_remove_vendor_is_vendor_vendor_is_grocery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='password',
        ),
    ]
