# Generated by Django 5.1.3 on 2024-12-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_remove_vendor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to='license'),
        ),
    ]
