# Generated by Django 5.1.3 on 2024-12-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0011_vendor_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='license',
            field=models.ImageField(default=1, upload_to='license'),
            preserve_default=False,
        ),
    ]
