# Generated by Django 5.1.3 on 2024-12-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_alter_vendor_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='license',
            field=models.ImageField(default=False, upload_to='license'),
        ),
    ]
