# Generated by Django 5.1.3 on 2024-12-20 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_vendor_alternate_email_vendor_otp_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='is_active',
        ),
    ]
