# Generated by Django 5.1.3 on 2025-01-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0018_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='since',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
