# Generated by Django 5.1.3 on 2025-01-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0019_vendor_since'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='vendors',
        ),
    ]
