# Generated by Django 5.1.3 on 2025-01-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0020_remove_category_vendors'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_pending_update_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pending_contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pending_fssai_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='fssai_certificate_pending'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pending_license',
            field=models.ImageField(blank=True, null=True, upload_to='license_pending'),
        ),
    ]
