# Generated by Django 5.1.3 on 2025-01-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0021_vendor_is_pending_update_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='is_vendor',
            field=models.BooleanField(default=True),
        ),
    ]
