# Generated by Django 5.1.3 on 2025-01-21 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0022_vendor_is_staff_vendor_is_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='store_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.storetype'),
        ),
    ]
