# Generated by Django 5.1.3 on 2025-01-30 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0023_category_store_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategorybyAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enable_subcategory', models.BooleanField(default=True)),
                ('subcategory_image', models.ImageField(blank=True, null=True, upload_to='clothing/subcategory/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubCategoriesbyAdmin', to='vendors.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubCategoriesbyAdmin', to='vendors.vendor')),
            ],
            options={
                'verbose_name_plural': 'Clothing Subcategories',
                'ordering': ['-created_at'],
                'unique_together': {('vendor', 'category')},
            },
        ),
    ]
