# Generated by Django 5.1.3 on 2025-01-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0024_subcategorybyadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategorybyAdmin',
        ),
    ]
