# Generated by Django 5.1.4 on 2025-02-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_checkout_checkoutitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment')], max_length=20),
        ),
    ]
