# Generated by Django 5.1.4 on 2025-04-24 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_checkout_coupon_code_checkout_coupon_discount_and_more'),
        ('fashion', '0028_alter_clothing_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='billing_address',
        ),
        migrations.AddField(
            model_name='checkout',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts_used', to='fashion.coupon'),
        ),
    ]
