# Generated by Django 5.1.4 on 2025-04-25 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_checkout_billing_address_checkout_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='shipping_address',
        ),
    ]
