# Generated by Django 5.1.4 on 2025-04-25 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_remove_checkout_shipping_address'),
        ('users', '0020_alter_coupon_created_by_alter_coupon_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='shipping_address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='users.address'),
        ),
    ]
