# Generated by Django 5.1.4 on 2025-04-25 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_checkout_shipping_address_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='shipping_address_id',
            new_name='shipping_address',
        ),
    ]
