# Generated by Django 5.1.4 on 2025-04-25 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_rename_shipping_address_id_checkout_shipping_address'),
        ('users', '0021_alter_coupon_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts_used', to='users.coupon'),
        ),
    ]
